import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { invoke } from '@tauri-apps/api/core';
import { ReportView, type ReportPayload } from '../src/features/report/ReportView';
import reportSourcePrivacy from './fixtures/report-source-privacy.json';

vi.mock('@tauri-apps/api/core', () => ({ invoke: vi.fn() }));

describe('analysis report', () => {
  beforeEach(() => { vi.mocked(invoke).mockReset(); });

  it('attributes each printed fact to its captured employee or explicit unknown without mutating the snapshot', () => {
    const original = structuredClone(reportSourcePrivacy.snapshot.payload);
    const first = original.facts[0];
    const payload = { ...original, employees: [
      { id: 'employee-a', masked_name: '旧甲**', employee_number: 'SYN-001' },
      { id: 'employee-b', masked_name: '旧乙**', employee_number: 'SYN-002' }],
      canonical_employees: [{ snapshot_id: 'employee-a', masked_name: '保存甲**', employee_number: 'SYN-001', department: '', job_title: '', lifecycle_status: 'active' }],
      facts: ['employee-a', 'employee-b', 'unknown'].map((employee_id, index) => ({ ...first, id: `fact-${index}`, employee_id })) };
    const before = JSON.stringify(payload);
    const { container } = render(<ReportView payload={payload as ReportPayload} onBack={vi.fn()} />);
    const rows = container.querySelectorAll('.report-finding');
    expect(rows[0]).toHaveTextContent('保存甲** · SYN-001');
    expect(rows[1]).toHaveTextContent('旧乙** · SYN-002');
    expect(rows[2]).toHaveTextContent('员工归属未匹配或待确认');
    expect(rows[0].closest('.print-hidden')).toBeNull();
    expect(JSON.stringify(payload)).toBe(before);
  });

  it('renders and prints masked fact and clause locations from the backend-verified fixture', () => {
    // Generated by the real service and checked against it by the Python suite.
    const { snapshot } = reportSourcePrivacy;
    const { container } = render(<ReportView payload={snapshot.payload as ReportPayload} saved={snapshot} onBack={vi.fn()} />);
    expect(container.textContent).not.toContain('13800138000');
    expect(container.textContent).not.toContain('13900139000');
    expect(screen.getAllByText(/合成联系人138\*\*\*\*8000/)).toHaveLength(2);
    expect(screen.getAllByText(/合成列139\*\*\*\*9000/)).toHaveLength(2);
    for (const source of screen.getAllByText(/合成联系人138\*\*\*\*8000/)) expect(source.closest('.print-hidden')).toBeNull();
  });

  function renderReport(scopePending = false) {
    render(
      <ReportView
        payload={{
          analysis_id: 'analysis-one',
          company_name: '完全虚构企业',
          generated_at: '2026-08-31T09:00:00Z',
          status: 'completed',
          is_demo: false,
          assessment_scope: {
            identifier: 'labor_materials_v1', display_label: '用工材料体检 v1',
            excluded_rule_codes: ['R09', 'R13', 'R14', 'R15'], excluded_rule_ids: ['A', 'B', 'C', 'D'],
            not_evaluated_reasons: { R16: '无法核实社保延续来源，本项暂未评估。' },
            payroll_evaluated: false, attendance_evaluated: false,
            settlement_document_label: '结算文件（final_pay），不要求工资表，不计算工资或补偿',
          },
          summary: {
            employee_count: 1,
            high_count: 1,
            medium_count: 0,
            low_count: 0,
            insufficient_data_count: 1,
            coverage_rate: 0.6,
            affected_employee_count: 1,
            requires_human_review_count: 1,
            deadline_30_count: 0,
            classification_pending: false,
          },
          material_coverage: { overall: 0.6, items: [], scope_pending: scopePending },
          employees: [{ id: 'employee-one', masked_name: '虚构员**', employee_number: 'F-100' }],
          findings: [
            {
              id: 'finding-one',
              rule_id: 'R01',
              title: '劳动合同签订事项待核查',
              severity_label: '高风险',
              status_label: '资料不足',
              requires_human_review: true,
              employee_name: '虚构员**',
              summary: '虚构合同缺少签署页',
              review_status: 'needs_material',
              recommended_actions: ['补充签署页'],
              reviews: [{ status: 'needs_material', note: '已通知补充虚构材料', created_at: '2026-09-07T10:00:00' }],
              sources: [
                {
                  file_name: '虚构合同.docx',
                  locator_type: 'paragraph',
                  location: { paragraph: 2 },
                },
              ],
            },
          ],
        }}
        onBack={vi.fn()}
      />,
    );
  }

  it('does not print a numeric coverage percentage while the workforce scope is unresolved', () => {
    renderReport(true);
    expect(screen.getByText('待确认')).toBeInTheDocument();
    expect(screen.queryByText('60%')).not.toBeInTheDocument();
  });

  it('keeps scope limitations in the printable report body', () => {
    renderReport();
    const scope = screen.getByRole('region', { name: '本次评估范围' });
    expect(scope).toHaveTextContent('用工材料体检 v1');
    expect(scope).toHaveTextContent('无法核实社保延续来源');
    expect(scope).not.toHaveClass('print-hidden');
  });

  it('renders findings and requests native printing through the real desktop bridge', async () => {
    let finishPrint!: () => void;
    vi.mocked(invoke).mockImplementation(() => new Promise<void>((resolve) => { finishPrint = resolve; }));
    renderReport();
    expect(screen.getByRole('heading', { name: '企业用工风险体检报告' })).toBeInTheDocument();
    expect(screen.getByText('完全虚构企业')).toBeInTheDocument();
    expect(screen.getByText(/虚构合同\.docx/)).toBeInTheDocument();
    expect(screen.getByText('报告草稿')).toBeInTheDocument();
    expect(screen.getByText('虚构合同缺少签署页')).toBeInTheDocument();
    expect(screen.getByText(/已通知补充虚构材料/)).toBeInTheDocument();
    expect(screen.getByText('补充签署页')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: '打印或保存 PDF' }));
    expect(invoke).toHaveBeenCalledWith('print_analysis_report');
    expect(invoke).toHaveBeenCalledOnce();
    expect(screen.getByRole('button', { name: '正在打开打印窗口…' })).toBeDisabled();
    finishPrint();
    await waitFor(() => expect(screen.getByRole('button', { name: '打印或保存 PDF' })).toBeEnabled());
  });

  it('shows a safe error if native printing fails and allows another attempt', async () => {
    vi.mocked(invoke).mockRejectedValueOnce(new Error('private native details')).mockResolvedValueOnce(undefined);
    renderReport();
    fireEvent.click(screen.getByRole('button', { name: '打印或保存 PDF' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('无法打开系统打印窗口，请重试。');
    expect(screen.queryByText(/private native details/)).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: '打印或保存 PDF' }));
    await waitFor(() => expect(invoke).toHaveBeenCalledTimes(2));
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });
});
